# Generated by Django 6.0.2 on 2026-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('eemail', models.EmailField(max_length=254, unique=True)),
                ('edept', models.CharField(max_length=50)),
                ('esalary', models.IntegerField()),
                ('econtact', models.CharField(max_length=15)),
                ('ejoindate', models.DateField()),
                ('ecity', models.CharField(max_length=40)),
            ],
        ),
    ]
